<script>
  import { createComponent } from './';

  export default createComponent({
    data() {
      return {
        hidden: false,
      };
    }, 
    props: {
      enabled: Boolean,
      fill: {
        type: String,
        default: 'black'
      }
    },
    created() {
      this.$watch(
        () => this.enabled,
        () => {
        if(!this.enabled) {
          setTimeout(() => {
            this.hidden = true
          }, 500);
        } else {
          this.hidden = false;
        }
      });
    }


  }); 
</script>

<template>
  <div class='loading-spinner-container'>
<!--
    <div v-if='!hidden' :class='{ loadingSpinnerOverlay: true, visible: enabled }'>
-->
      <svg v-if='enabled'
        class="loading-spinner" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <g transform="rotate(0 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.9166666666666666s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(30 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.8333333333333334s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(60 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.75s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(90 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.6666666666666666s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(120 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5833333333333334s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(150 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.5s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(180 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.4166666666666667s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(210 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.3333333333333333s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(240 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.25s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(270 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.16666666666666666s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(300 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="-0.08333333333333333s" repeatCount="indefinite"></animate>
          </rect>
        </g><g transform="rotate(330 50 50)">
          <rect x="47" y="24" rx="3" ry="6" width="6" height="12" v-bind:fill='fill'>
            <animate attributeName="opacity" values="1;0" keyTimes="0;1" dur="1s" begin="0s" repeatCount="indefinite"></animate>
          </rect>
        </g>
        <!-- [ldio] generated by https://loading.io/ -->
        </svg>
<!--
      </div>
-->
    <slot></slot>
  </div>
</template>

<style>
  .loading-spinner-container {
    position: relative;
  }
/*
  .loadingSpinnerOverlay {
    position: fixed;
    width: 100%;
    height: 100%;
    left: 0;
    top: 0;
    background: rgba(0, 0, 0, 0.5); 
    display: flex;
    justify-content: center;
    align-items: center;
    animation: fade-out 500ms;
    opacity: 0;
  }
*/
  .loadingSpinnerOverlay.visible {
    animation: fade-in 500ms;
  }

  @keyframes fade-out {
    from {opacity: 1;}
    to {opacity: 0;}
  }

  @keyframes fade-in {
    from {opacity: 0;}
    to {opacity: 1;}
  }

  .loading-spinner {
    width: auto;
    height: 4em;
    display: inline;
    shape-rendering: auto;
  }
</style>
